"""Reusable UI components."""

import streamlit as st


def render_header():
    """Render the application header."""
    st.markdown('<h1 class="main-header">🛡️ DeepShield AI - Deepfake Detection System</h1>', unsafe_allow_html=True)
    st.markdown(
        '<p class="sub-header">Advanced AI-Generated Image Detection Using EfficientNetB7 with Attention Mechanism</p>',
        unsafe_allow_html=True
    )
    st.markdown("---")


def render_sidebar():
    """Render the streamlined sidebar and return debug state only."""
    with st.sidebar:
        # The app now uses a fixed EfficientNet pipeline, so the sidebar only
        # exposes a compact status panel.
        st.markdown("""
        <div style='background: linear-gradient(135deg, rgba(255,255,255,0.18) 0%, rgba(255,255,255,0.08) 100%);
                    padding: 1.35rem 1.15rem; margin: -1rem -1rem 1rem -1rem;
                    border-radius: 0 0 20px 20px; box-shadow: 0 4px 15px rgba(0,0,0,0.3);'>
            <div style='text-align: center;'>
                <div style='background: rgba(255,255,255,0.18); width: 54px; height: 54px;
                           border-radius: 50%; margin: 0 auto 1rem auto; display: flex;
                           align-items: center; justify-content: center;
                           box-shadow: 0 4px 10px rgba(0,0,0,0.2);'>
                    <span style='font-size: 2rem;'>⚙️</span>
                </div>
                <h2 style='color: #ffffff; font-size: 1.5rem; font-weight: 800; margin: 0;
                           text-shadow: 0 2px 4px rgba(0,0,0,0.3); letter-spacing: 0.5px;
                           -webkit-font-smoothing: antialiased;'>
                    OPTIMIZED PIPELINE
                </h2>
                <p style='color: rgba(255,255,255,0.9); font-size: 0.88rem; margin: 0.45rem 0 0 0;
                          font-weight: 500;'>
                    EfficientNet preprocessing is always enabled
                </p>
            </div>
        </div>
        """, unsafe_allow_html=True)

        return False


def render_footer():
    """Render the application footer."""
    st.markdown("---")
    st.markdown("### 📋 About This System")

    # Feature Cards
    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("""
        <div style='background: #ffffff;
                    padding: 2rem; border-radius: 15px;
                    border: 2px solid #3182ce;
                    box-shadow: 0 8px 20px rgba(0,0,0,0.1); margin-bottom: 1rem;'>
            <h4 style='color: #2c5282; margin-bottom: 1.5rem; font-size: 1.3rem; font-weight: 700;'>
                🔬 Technical Architecture
            </h4>
            <ul style='list-style: none; padding: 0; margin: 0;'>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>EfficientNetB7</strong> convolutional backbone
                </li>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>Custom attention mechanism</strong> enhancing feature discrimination
                </li>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>Large-scale training dataset</strong> comprising authentic and synthetic images
                </li>
                <li style='padding: 0.75rem 0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>Robust performance</strong> across diverse deepfake generation methods
                </li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

    with col_b:
        st.markdown("""
        <div style='background: #ffffff;
                    padding: 2rem; border-radius: 15px;
                    border: 2px solid #805ad5;
                    box-shadow: 0 8px 20px rgba(0,0,0,0.1); margin-bottom: 1rem;'>
            <h4 style='color: #553c9a; margin-bottom: 1.5rem; font-size: 1.3rem; font-weight: 700;'>
                ✨ Detection Capabilities
            </h4>
            <ul style='list-style: none; padding: 0; margin: 0;'>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    Synthetic images generated by <strong style='color: #1a202c;'>GANs</strong> (Generative Adversarial Networks)
                </li>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>Diffusion-based models</strong> (Stable Diffusion, DALL-E, Midjourney)
                </li>
                <li style='padding: 0.75rem 0; border-bottom: 2px solid #e2e8f0; color: #2d3748; font-size: 1rem;'>
                    Alternative <strong style='color: #1a202c;'>generative AI architectures</strong>
                </li>
                <li style='padding: 0.75rem 0; color: #2d3748; font-size: 1rem;'>
                    <strong style='color: #1a202c;'>Resilient</strong> to post-processing and compression artifacts
                </li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

    return
